version: "3.9"

services:
  http_client:
    container_name: http_client
    build: 
      context: ./
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    networks:
      - public_network
    restart: always

networks:
  public_network:
    driver: bridge